### ISSUE TITLE
jsaddle-warp - Always render jsaddle page regardless of url (for client side routing)

### ISSUE THREAD

**Issue by peacememories** [ghcjs/jsaddle#34]
The title basically says it all. It would be neat to have jsaddle automatically serve the application on every url, so client side routing can be developed.

Of course this could be behind an option or via a different function etc.

**Comment by m0ru** [comment]
e.g. if the SPA uses `"/"`, `"/new"`, `"/post/<postId>"` it would be nice to reload the page on any of these and continue debugging.
(our current work-around is to use fragment-identifiers; however, should reflex-dom implement static-prerendering javascript-less navigation becomes a possibility and fragment-identifiers are rather suboptial for that)

**Comment by ryantrinkle** [comment]
@m0ru Agreed!

Also, you might be pleasantly surprised to learn that reflex-dom has supported [static rendering](https://github.com/reflex-frp/reflex-dom/blob/a20e829214e5330a2d829bcf156046b1fe24a169/reflex-dom-core/src/Reflex/Dom/Builder/Static.hs#L283) for quite some time.

**Comment by m0ru** [comment]
ah, yes, i forgot ^^"
afair we tried it while setting up the project but ran into problems when inflating it on the client (using the static rendering as pre-render to speed up page-loading)

**Comment by ryantrinkle** [comment]
@m0ru Ah, interesting.  I'd love to know what you ran into - maybe it's stuff we can fix!

**Comment by m0ru** [comment]
Hm, apparently I didn't commit that experiment to our project, but I can recreate it when I get to my own notebook where stuff is properly set up.

1. Basically i created an app along the lines of `main = run 8081 $ mainWidget $ el "input" blank`
2. compile it with ghcjs 
3. in the resulting html edit the initial value / content of the input (or div or whatever)
4. run the app
5. the input should be gone / overwritten by the starting app

I wanted to test, that if the app is send with statically pre-generated html, people start typing in the input-field (or textarea) and *then* the javascript finishes bootin and kicks in, that whatever people wrote wasn't lost. Thus to check, whether the renderer merges changes over existing DOM or just replaces it with the dynamically generated one.

**Comment by ryantrinkle** [comment]
It does replace with the dynamically generated one.  It's careful to make sure the switchover is instantaneous, but it does not make any attempt to reuse existing elements.  What we've done in the past is disable all input elements on the page using [runInputDisabledT](https://github.com/reflex-frp/reflex-dom/blob/a20e829214e5330a2d829bcf156046b1fe24a169/reflex-dom-core/src/Reflex/Dom/Builder/InputDisabled.hs#L31) when drawing the page statically, so that the user can't start entering information until the JS loads.

It would be great if we could take over the DOM instead, but it would take some work to get there.
