### ISSUE TITLE
jsaddle-warp does not seem to handle multiple clients well

### ISSUE THREAD

**Issue by eskimor** [ghcjs/jsaddle#57]
It seems that jsaddle-warp does not properly handle multiple browser connections well. It seems that they get mixed somehow. I just had the issue, that one private tab requested data from the server and it showed up in the GUI of the other tab, when I closed the private tab. (It did not show up in the private tab at all).

Also when tracing what gets sent to the server it seems that data gets mixed. Can this be the case? Is jsaddle-warp designed to handle multiple connections well?

**Comment by hamishmack** [comment]
It should work.  Do you have a test case that we can use to reproduce the issue?  Was the server just plane JSaddle (or have you added servant or anything else to it)?  Was it using the JSaddle `debug` function?  What other libraries were being used?

One thing that might cause problems is if JSaddle, other libraries or your app are using `unsafePerformIO` to create singletons.  JSaddle does use this trick, but only in places it should be safe.  For instance it has `jsNull = JSVal . unsafePerformIO $ newIORef 0`.  This should be ok because the IORef inside any JSVal should be immutable (it is an IORef so we can attach finalisers for the JSVals that need to be freed on the JavaScript side).

**Comment by eskimor** [comment]
Thank you for this very quick response. I have a test case, but it is far from minimal, I will try to provide a minimal one and will prepare and post instructions for the not so minimal case in the meantime.

I was not using the JSaddle 'debug' function. Other libraries used:

```
aeson
attoparsec
base64-bytestring
bytestring
Cabal
containers
data-default
directory
errors
filepath
generic-deriving
ghcjs-dom
gonimo-common
http-types
jsaddle
jsaddle-dom
jsaddle-warp
lens
lifted-base
mtl
reflex
reflex-dom
reflex-dom-core
safe
text
time
transformers
transformers-base
wai-middleware-static
warp
websockets
```
At least my code does not make any use of unsafePerformIO.

Servant was not added, just a middleware serving static files, code is [here](https://github.com/gonimo/gonimo/blob/master/front-warp/app/Warp.hs#L30).

**Comment by eskimor** [comment]
Ok, I am no longer able to reproduce this issue. Really weird, maybe my system just needed a reboot.
